language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
env:
  global:
  - secure: gM0qvYsJmnO74D7eZr1JS9640iY5ewE9WaMLwhos2vkanQtqHuwwsXKJprFPUeBMZYBHO29pnwNFw+1+KCkKJl7Ge48yS4ubn4+48feMzs21aJpDh0EbHrme7IED0UglU6LWgmjhiB9b4n/zRVbTShAWj1c+ljJODt2qHT8iJtM=
  - secure: bAJ0eWTyUOWmIQ9CLsyL9RogwzaiKj74LFVDsIWDjMi5L6MXos6xmiLY5htkDUeZDSXFvkzCIOHdwbGy+YOH3ACcxrFYyXqx4PMzjKh+hgvmqnZDgIbeLSXvgmvGV3/45RUFpvkx8//CjqX9IfcspR1yeyvRE8v01/Rtao6Iu4M=
