language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
env:
  global:
  - secure: e6DUBIKWA3MKrCmUBCGvEU05PyYOl43W+YeHfbqFiUt4hX0K5w8S62IRgxHjPcgpS9tMmwcQXl7bIVpdkWH9qPeS7jpQdMhCeVSKLVXoKhbjhkjNb+/KRjiRjnSl6bmWd668/1inpaPLFkzCnzCvNfbHpHlaktwO1s4CKLXkHAw=
  - secure: Bx+znA+jPgys/ZnElYjDNt7Op3MxAL1jxOmhmZGIFOfwBnzLmcjkrFj8pPnoLMwMFRxHd9nc3WC4cBc1bZbErKh60w2rEdvGTZmBQKkbMB4eVxAVQ83lfLPP+HKlicg3Q6F6K72iQvCB0yIodDwCb8A+CsRXbSHMA2YCvWl9orU=
